apiVersion: v1
kind: Service
metadata:
  name: loki-lb
  namespace: loki
spec:
  type: LoadBalancer
  selector:
    app.kubernetes.io/name: loki
  ports:
    - name: http
      port: 3100
      targetPort: 3100
      protocol: TCP
