apiVersion: v1
kind: Service
metadata:
  name: k6-dashboard-service
  namespace: default
spec:
  type: LoadBalancer
  selector:
    app: k6
  ports:
    - name: http
      port: 80
      targetPort: 5665
      protocol: TCP
